### PR TITLE
Truth table style unit tests for `and` conditional

### PR DESCRIPTION
**Pull request by alallier**

### CODE REVIEW

**Comment by kethinov** [comment]
same issue as [here](https://github.com/kethinov/teddy/pull/67#issuecomment-273880371)

**Comment by alallier** [comment]
Updated to one test and one template. Let me know if you want any change to wording

**Comment by kethinov** [comment]
this test passes... is it supposed to pass?

**Comment by kethinov** [comment]
also merge conflict

**Comment by alallier** [comment]
Resolved merge conflict and no it wasn't suppose to pass I fixed the testing value

**Pull request merged**
